<h1><?php echo $this->__('Order List') ?></h1>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php if(!$this->getRequest()->getParams()) : ?>
<div class="show_button button"><?php echo $this->__('Show Filter') ?></div>
<?php else: ?>
<div class="show_button button"><?php echo $this->__('Hide Filter') ?></div>
<?php endif ?>
<form method="get" id="form-filter-product" <?php if(!$this->getRequest()->getParams()) : ?>style="display:none;"<?php endif ?>>
	<fieldset>
	    <div class="col2-set">
	        <div class="col-1">
	            <ul class="form-list">
                    <li>
                        <label for="filter-order_number"><?php echo $this->__('Order Number') ?></label><br/>
                        <input id="filter-order_number" name="filter_order_number" title="<?php echo $this->__('Order Number') ?>" type="text" class="input-text" style="width:160px;" value="<?php echo $this->getRequest()->getParam('filter_order_number') ?>" />
                    </li>
	                <li>
	                    <label for="filter-name"><?php echo $this->__('Customer Name') ?></label><br/>
	                    <input id="filter-name" name="filter_name" title="<?php echo $this->__('Customer Name') ?>" type="text" class="input-text" style="width:160px;" value="<?php echo $this->getRequest()->getParam('filter_name') ?>" />
	                </li>
	            </ul>
	        </div>
	        <div class="col-2">
	            <ul class="form-list">
	                <li>
	                    <label for="filter-status"><?php echo $this->__('Order Status') ?></label><br/>
	                    <select id="filter-status" name="filter_status" title="<?php echo $this->__('Order Status') ?>"  style="width:160px;">
		                <?php $_status = (string)$this->getRequest()->getParam('filter_status') ?>
	                    <?php foreach($this->getOrderStatusOptions() as $option) : ?>
	                        <option value="<?php echo $option['status'] ?>" <?php echo $_status===$option['status']?'selected="selected"':'' ?>><?php echo $option['label'] ?></option>
	                    <?php endforeach; ?>
	                    </select>
	                </li>
	                <li>
	                    <label for="filter-date"><?php echo $this->__('Order Date') ?></label><br/>
	                    <input id="filter-date" name="filter_order_date" title="<?php echo $this->__('Order Date') ?>" type="text" class="input-text" style="width:100px;" value="<?php echo $this->getRequest()->getParam('filter_order_date') ?>" />
<img title="<?php echo $this->__('Select Date') ?>" id="filter-date-trigger" src="<?php echo $this->getSkinUrl('images/calendar.gif');?>" style="display: inline; "/>
	                </li>
	            </ul>
	        </div>
	    </div>
		<div class="button-set">
			<input type="submit" value="search" style="display:none" />
            <input type="hidden" name="limit" value="<?php echo $this->getRequest()->getParam('limit')?>"/>
            <?php $paramP = $this->getRequest()->getParam('p'); ?>
            <input type="hidden" name="p" value="<?php echo ($paramP === '' || $paramP === NULL) ? '1' : $paramP ?>"/>
	        <button class="button" name="reset_filter" type="button" onclick="setLocation('/pim/order/list')" id="filter-reset" value="reset"><span><?php echo $this->__('Reset Filter') ?></span></button>
            <button class="button" name="submit_action" type="submit" id="filter-search" value="search"><span><?php echo $this->__('Search') ?></span></button>
        </div>
	</fieldset>
</form>
<br>
<fieldset>
	<?php echo $this->getChildHtml('toolbar') ?>
    <table cellspacing="0" cellpadding="0" class="data-table">
        <col width="" />
        <col width="" />
		<col width="" />
        <col width="" />
        <thead>
            <tr>
                <th><?php echo $this->__('Order Date')?></th>
                <th><?php echo $this->__('Order Number')?></th>
                <th><?php echo $this->__('Name')?></th>
                <th><?php echo $this->__('Status')?></th>
            </tr>
        </thead>
        <tbody>
		<?php foreach ($this->getOrderCollection() as $order): $id = $order->getId(); ?>
			<tr>
				<td>
					<?php echo $this->htmlEscape($order->getCreatedAt()); ?>
				</td>
				<td>
					<a href="<?php echo Mage::getBaseUrl().'pim/order/view?id='.$id?>"><?php echo $this->htmlEscape($order->getIncrementId()); ?></a>
				</td>
				<td>
					<?php echo $this->htmlEscape($order->getCustomerFirstname().' '.$order->getCustomerLastname()); ?>
				</td>
				<td>
					<?php echo $this->htmlEscape($order->getStatus()); ?>
				</td>
			</tr>
		<?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->getChildHtml('toolbar') ?>
</fieldset>

<script type="text/javascript">
jQuery(function() {
	jQuery('.show_button').on('click',function() {
		if(jQuery('#form-filter-product').css('display') == 'block') {
			jQuery('#form-filter-product').slideUp('fast');
			jQuery('.show_button').text('Show Filter');
		} else {
			jQuery('#form-filter-product').slideDown('fast');
			jQuery('.show_button').text('Hide Filter');
		}

	});
});
</script>
